name: playx_version_update
description: Easily show material update dialog in Android or Cupertino dialog in IOS with support for Google play in app updates.
version: 0.0.1

environment:
  sdk: '>=3.0.3 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4
  package_info_plus: ^4.0.2
  version: ^3.0.2
  url_launcher: ^6.1.11
  dio: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.sourcya.playx_version_update
        pluginClass: PlayxVersionUpdatePlugin

